### ISSUE TITLE
amqp connection timeout 

### ISSUE THREAD

**Issue by BhaskaranR** [seneca-contrib/seneca-amqp-transport#41]
Hi,
I am getting a time out exception when i try to connect a service running locally to rabbit mq instance which is running on a docker container. I could access the uri on the browser through. http://127.0.0.1:15672 works good and brings up the admin screen. am i not setting something?

08:52:14 karmasoc-user-0 Seneca Fatal Error
08:52:14 karmasoc-user-0 ==================
08:52:14 karmasoc-user-0 Message: seneca: gate-executor: [TIMEOUT:cskfllwwm4bi/qniojukx66dg:11111<1469969534677-1469969523565:undefined]
08:52:14 karmasoc-user-0 Code: transport_listen
08:52:14 karmasoc-user-0 Details: { type: 'amqp',
08:52:14 karmasoc-user-0   url: 'amqp://guest:guest@127.0.0.1:15672',
08:52:14 karmasoc-user-0   pin: 'role:user',
08:52:14 karmasoc-user-0   'orig$': 
08:52:14 karmasoc-user-0    { Error: [TIMEOUT:cskfllwwm4bi/qniojukx66dg:11111<1469969534677-1469969523565:undefined]
08:52:14 karmasoc-user-0        at Timeout._onTimeout (/Users/bhaskarferrari/Documents/karmasoc/karmasoc-user/node_modules/gate-executor/gate-executor.js:112:21)
08:52:14 karmasoc-user-0        at tryOnTimeout (timers.js:224:11)

**Comment by nfantone** [comment]
Hi, @BhaskaranR. I believe you're trying to connect to the web admin interface, rather than the AMQP port. 15672 is usually reserved for the admin, while [5672 is the default port](https://www.rabbitmq.com/networking.html) on which RabbitMQ listens for connections.

Try connecting to `amqp://guest:guest@127.0.0.1:5672`.

Also, depending on the version of RabbitMQ you've installed, the `guest` account might be disabled by default.

**Comment by BhaskaranR** [comment]
@nfantone  thanks for pointing it out. It works!
