### ISSUE TITLE
How to make the queue NOT durable? / How to stop msg replay?

### ISSUE THREAD

**Issue by combsco** [seneca-contrib/seneca-amqp-transport#44]
I've tried...

Deleting the queues and exchange and I'm still getting a durable **queue** in RabbitMQ

Using per Readme:
`seneca.use('seneca-amqp-transport', { queues: { action: { options: { durable: false } } } })`

**Comment by combsco** [comment]
Actually durable queue may not even my biggest concern... let's say a message creates an error... puts a Seneca service into a crash loop.

No way to recover except to purge/delete the queue so the service can come back online.

**Comment by nfantone** [comment]
@combsco Hi! Thanks for letting me know about your issues.

You are right. In both regards.

1) The usage example on the `README.md` was wrong. Fixed in #45.
2) So, yes - if a client fails to process the payload _before_ it actually gets to the listener function, the microservice will crash. It's not currently under your control. And it'll "put Seneca into a crash loop", as you mentioned. This _may_ or _may not_ be what you want. Although, support for [dead lettering](https://www.rabbitmq.com/dlx.html) is on our little [roadmap](https://github.com/seneca-contrib/seneca-amqp-transport#roadmap) and it may eventually paliate issues like yours, it's not really high on priority since most of the time if a "crash loop" begins it's a sign that some _other_ microservice might be "misbehaving" by, say, sending improper payloads or declaring stuff on the AMQP broker that are already declared with different settings. In all those cases, you should manually intervene by monitoring queues' activity and taking actions (like purging messages, examine them or log them). 

I know it may not _sound_ ideal, but I've found that, in practice, it's not really a _bad_ approach at all, since:

  - It may let you detect defects on your ecosystem earlier/faster and act upon them.
  - It doesn't deter the service ability to keep handling incoming messages: just spawn multiple listener scripts and declare more than one consumer per queue. If _all_ your consumers fail (that is, all node processes loop and crash), then there's definitely something wrong somewhere and those microservice need to be stopped and diagnosed.

**Comment by nfantone** [comment]
After reading what I've posted above, I felt the need to clarify: that only applies to errors produced _before_ Seneca has the chance to call your

**Comment by combsco** [comment]
I agree on all points. I ran into this problem passing a message to a Users service ran by Seneca. However, my database throws a 'User Not Found' error which is fine but instead of Seneca properly handling that with my error handlers. It just throws a FATAL error and crashes the process.

Which is how I got to question #2 ... 1 message put my service into a crash loop until Kubernetes got tired and left it offline.

**Comment by nfantone** [comment]
@combsco If I understood you correctly, you have one microservice trying to communicate to another to fetch some user data. And the service accesing the database throws an error. Is that error being catch and sent to the requester? If you don't explicitly handle it, the listener will fail with a `FATAL` error and the client will end up crashing with a `TIMEOUT` error.

**Comment by combsco** [comment]
**Note**: This may or may not be seneca-amqp-transport's fault but might be Seneca error handling in general which there's an open issue somewhere for. Also I don't have **fatal$** set to true so it shouldn't just call everything FATAL. However, oddly enough this works and Seneca returns the error to the API when communicating over the default transport (REST).

**Pipeline**: Client (Postman) <-> API Gateway <-> RabbitMQ <-> User Service

a piece of User service code...
Bookshelf.js is the ORM in use here.
```js
  const error = require('eraro')({package: 'user'})
  // Other stuff and add's.

  seneca.add({ role: 'user', cmd: 'getOne' }, (msg, done) => {
    new User()
      .query('where', { id: msg.payload.user_id }, { tenant_id: msg.payload.tenant_id })
      .fetch({ require: true })
      .then((user) => {
        return done(null, user.toJSON())
      })
      .catch(User.NotFoundError, () => {
        return done(error('nfe', 'User Not Found'))
      })
      .catch((err) => {
        return done(err, null)
      })
  })
```

API Gateway knows how to handle an error returned if Seneca actually responded with an Error vs Crashing.

```text
Seneca Fatal Error
==================

Message: seneca: Action cmd:getOne,role:user failed: user: User Not Found.

Code: act_execute

Details: { message: 'user: User Not Found',
  pattern: 'cmd:getOne,role:user',
  fn: [Function],
  cb: [Function],
  instance: 'Seneca/2.1.0/jwnuqlxj6sp9/1471900975806/15/userService',
  'orig$': 
   { Error: user: User Not Found
       at errormaker (/usr/src/node-app/node_modules/eraro/eraro.js:94:15)
       at User.query.fetch.then.catch (/usr/src/node-app/src/user.js:99:21)
       at tryCatcher (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/util.js:26:23)
       at CatchFilter.doFilter (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/catch_filter.js:40:36)
       at CatchFilter.<anonymous> (/usr/src/node-app/node_modules/continuation-local-storage/context.js:76:17)
       at CatchFilter.tryCatcher (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/util.js:26:23)
       at Promise._settlePromiseFromHandler (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:507:31)
       at Promise._settlePromiseAt (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:581:18)
       at Promise._settlePromises (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/promise.js:697:14)
       at Async._drainQueue (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:123:16)
       at Async._drainQueues (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:133:10)
       at Immediate.Async.drainQueues (/usr/src/node-app/node_modules/bookshelf/node_modules/bluebird/js/main/async.js:15:14)
       at Immediate.<anonymous> (/usr/src/node-app/node_modules/async-listener/glue.js:188:31)
       at runCallback (timers.js:566:20)
       at tryOnImmediate (timers.js:546:5)
       at processImmediate [as _immediateCallback] (timers.js:525:5)
     eraro: true,
     orig: null,
     code: 'nfe',
     user: true,
     package: 'user',
     msg: 'user: User Not Found',
     details: {},
     callpoint: 'at User.query.fetch.then.catch (/usr/src/node-app/src/user.js:99:21)' },
  'message$': 'user: User Not Found',
  plugin: {} }

Instance: Seneca/2.1.0/jwnuqlxj6sp9/1471900975806/15/userService
  ALL ERRORS FATAL: action called with argument fatal$:true (probably a plugin init error, or using a plugin seneca instance, see senecajs.org/fatal.html)
    at act_done (/usr/src/node-app/node_modules/seneca/seneca.js:1234:29)
```

**Comment by nfantone** [comment]
Ok, so a couple of pointers here and there. Let's review your source code, a little bit:

```js
  const error = require('eraro')({package: 'user'})
  // Other stuff and add's.

  seneca.add({ role: 'user', cmd: 'getOne' }, (msg, done) => {
    new User()
      .query('where', { id: msg.payload.user_id }, { tenant_id: msg.payload.tenant_id })
      .fetch({ require: true })
      .then((user) => {

        // No need to call .toJSON, which is used internally by JSON.stringify, 
        // which is then used by the transport to serialize your response.
        // Just `done(null, user)` will do.
        return done(null, user.toJSON())
      })
      .catch(User.NotFoundError, () => {

        // Here's your problem: by calling the callback with an error parameter,
        // you are effectively telling Seneca that an unrecoverable issue occurred
        // and won't reply to the client. In order to do that, you need to pass `null`
        // as the first parameter and the error as the result of your operation.
        // Like so: `done(null, error('nfe', 'User Not Found'))`
        return done(error('nfe', 'User Not Found'))
      })
      .catch((err) => {
        // No need for `null` here, unless you were trying to be extra explicit
        return done(err, null)
      })
  })
```

Also,

> I don't have fatal$ set to true so it shouldn't just call everything FATAL.

- `$fatal` defaults to `true`. All errors are considered "fatal" unless explicitly told otherwise.
- I don't know if `eraro` creates `Error` objects out of your parameters. If that's the case,  some `Error`'s properties are typically not enumerable and thus not not serialized to JSON. So not all of the information may get to the client. Check that out.

**Comment by nfantone** [comment]
@combsco Any news on this? `1.0.1` was released to npm with that minor doc fix for the bug you pointed out.

Feel free to close the issue if you do not have any further queries.

**Comment by combsco** [comment]
Sorry for my late response. I decided to stop using Seneca and to use Coworkers for microservices. So we can close this issue. Thanks @nfantone

**Comment by nfantone** [comment]
[Coworkers](https://www.npmjs.com/package/coworkers) looks nice! Didn't know about it. Hope it helps you solve your scenario better.
